### ISSUE TITLE
Server sent charset unknown to the client

### ISSUE THREAD

**Issue by borisdiakur** [nezhar/wordpress-docker-compose#10]
I’ve done a `docker-compose pull` today and now after a `docker-compose up` I’m getting this:

```sh
wordpress_1  | Warning: mysqli::mysqli(): Server sent charset (255) unknown to the client. Please, report to the developers in - on line 22
wordpress_1  | 
wordpress_1  | Warning: mysqli::mysqli(): (HY000/2054): Server sent charset unknown to the client. Please, report to the developers in - on line 22
wordpress_1  | 
wordpress_1  | MySQL Connection Error: (2054) Server sent charset unknown to the client. Please, report to the developers
my_wordpress_1 exited with code 1
```

Any idea what’s wrong here?

**Comment by borisdiakur** [comment]
Fixed it in the docker-compose.yaml by changing

```yaml
db:
    image: latest
```

to

```yaml
db:
    image: mysql:5.7
```

The issue seems to be that MySQL 8 changed the default charset to utfmb4. Is there maybe a better solution than sticking to mysql 5.7?

**Comment by nezhar** [comment]
Hi @borisdiakur 

Thanks for bringing this to my attention :). I think your fix would be ok in most cases.
To change the charset it requires some extra configurations: https://hub.docker.com/_/mysql/ (see **Configuration without a cnf file**)

On my machine I got an error regarding the authentication to the db. So I will also include the option to revert to the **mysql_native_password** plugin for authentication in the docker-compose.yml

```
  db:
    image: mysql:5.7
    ports:
      - 127.0.0.1:3306:3306 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wordpress-network
```
