### ISSUE TITLE
Export.sh cant connect to local MySQL

### ISSUE THREAD

**Issue by jjburr** [nezhar/wordpress-docker-compose#14]
When executing export.sh it cannot connect to MySQL error 2002

![image](https://user-images.githubusercontent.com/31635161/48092615-0900da00-e272-11e8-873f-393a73dfc9fe.png)

**Comment by nezhar** [comment]
This looks like the database container is not running. Does this also happen when you run `docker-compose up`?

**Comment by sophiekovalevsky** [comment]
@nezhar the same is happen to me. I verified that the db container is running. However, when I execute the export script, it creates the file, but appear the same message within the file. Then, instead of dupming the db, it shows the message. Any idea of why this is happening? 
Thanks in advance,

**Comment by alabius** [comment]
@nezhar I have same issue with mine too
and also, how can I login into the mysql container

**Comment by cmmartin** [comment]
Confirmed it's working now
