### ISSUE TITLE
[Feature Request] Build XDebug into PHP config?

### ISSUE THREAD

**Issue by jschrab-lc** [nezhar/wordpress-docker-compose#16]
Would it be within the goals of the project to have XDebug be part of the PHP configuration? Or is there intention for this container configuration to be used for production purposes too?

Or has someone done this on their own already and have a few bullet points to share on how to set it up?

**Comment by nezhar** [comment]
The containers are for development, XDebug would be a great integration.
It is also not that complicated, I have an old gist here:
https://gist.github.com/nezhar/27bddc6cc44a3e2e44819bd8dcbc289c

The documentation should be also extended in this case.

**Comment by mwoodpatrick** [comment]
Any ETA for this it would be very handy

**Comment by PiotrCzapla** [comment]
I've build add xdebug, wpcli and few other tools and wrapped this as vscode .devcontainer, feel free to try it:
https://github.com/PiotrCzapla/vscode-wordpress

There is as well a Dockerfile that installs all the necessary tools along with the XDEBUG. 
https://github.com/PiotrCzapla/vscode-wordpress/blob/main/.devcontainer/Dockerfile

You can try to use it if you don't want to use vscode.
