### ISSUE TITLE
Wordpress cannot modify database

### ISSUE THREAD

**Issue by notacompletemoron** [nezhar/wordpress-docker-compose#26]
I followed your guide, and now I'm getting the following issues;

`WordPress database error: [View 'information_schema.COLUMNS' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them]
SHOW FULL COLUMNS FROM "wp_options"`

There are literally dozens of these errors.

How can I resolve this issue?

**Comment by notacompletemoron** [comment]
Nvm, I got it. Had to do a clean install, and purge every single last docker and compose related file.

**Comment by nezhar** [comment]
It appears that something broke on import/setup. Glad you found a way to work it out :+1:
