### ISSUE TITLE
Can't import an existing site

### ISSUE THREAD

**Issue by arimourao** [nezhar/wordpress-docker-compose#27]
I tried to run an existing site into this container following the docs. No success, I just get a blank screen of death. It is creating succesfully the database from the export and I can debug (with die()) several files inside the wp-app folder. Not exactly if this is an issue with this compose file, but do you have any idea why is this happening?

**Comment by nezhar** [comment]
Check if the `wp-config.php` points to the DB specified in the docker-compose.yml.
```
WORDPRESS_DB_HOST: db
WORDPRESS_DB_NAME: wordpress
WORDPRESS_DB_USER: root
WORDPRESS_DB_PASSWORD: password
```

Also make sure to define your website home and site url:
```
define('WP_HOME','http://wp-app.local');
define('WP_SITEURL','http://wp-app.local');
```
This way you don't have to replace it in the database.
