### ISSUE TITLE
Cannot find local files

### ISSUE THREAD

**Issue by pdmwu** [nezhar/wordpress-docker-compose#29]
I'm new to Docker. Your bundle is cool. But I cannot find the local WordPress and database files. Where are the volumes locally on my harddisk?

**Comment by nezhar** [comment]
They are managed by Docker. For compatibility across all operating systems that docker runs on, we have used the docker internal volumes. You can also use volumes that are mounted directly to your file system, but sometimes you can have issues, depending on the OS. You should take a look at the docs if you want to find out more about volumes: https://docs.docker.com/storage/volumes/
