### ISSUE TITLE
Cannot start as a service

### ISSUE THREAD

**Issue by crerem** [nezhar/wordpress-docker-compose#36]
I'm trying to use the docker-compose.yml to start the wordpress as a service. 

docker stack deploy -c docker-compose.yml wp1

However, the mysql container is not starting and is failing with this error

```
time="2019-09-26T12:06:30Z" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/4f6b0c7286856ee9fd726cf1ce957103f62b7f39ee9f321584da250ea3a91acd/shim.sock" debug=false pid=13893
time="2019-09-26T12:06:31Z" level=info msg="shim reaped" id=4f6b0c7286856ee9fd726cf1ce957103f62b7f39ee9f321584da250ea3a91acd
time="2019-09-26T12:06:31.298552013Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
time="2019-09-26T12:06:31.526719243Z" level=error msg="fatal task error" error="task: non-zero exit (1)" module=node/agent/taskmanager node.id=o5eezulizx214m5effwasb1nc service.id=x1i0e0sea1qi4g8jj2hu3vgvl task.id=zo8oi32rt2w12daqu9x1v7c1l
```

If i do a docker-compose up everything works as expected.
Any idea why ?
Thank you

**Comment by nezhar** [comment]
The purpose if this repository is to create a development environment, not containers that should be used in production.
Is there any advantage to run the containers as a service rather then with `docker-compose` directly?
