### ISSUE TITLE
apache and mysql is not starting

### ISSUE THREAD

**Issue by geeksupport1** [nezhar/wordpress-docker-compose#39]
Hi nezhar, 

Thanks for sharing this.

I git clone this directory and type in 

docker-compose up
The apache service is not starting. 

Any ideas.

I am running ubuntu on windows 10 pro wsl

I have tried running other forms docker like visiblevc ,etc, and they start.

 `
geek@DESKTOP-O7A5KCN:/e/PROJECT/DOCKER/MYCHILDCARE$ docker-compose up
Starting _db_1 ...
Starting _db_1 ... done
Starting _wp_1 ...
Starting _wp_1
Starting _pma_1 ...
Starting _wp_1 ... done
Starting _wpcli_1 ...
Starting _wpcli_1 ... done
Attaching to _db_1, _wp_1, _pma_1, _wpc
db_1     | 2019-10-28 12:35:28+00:00 [Note] [Entrypoint]: Entrypoint script for MyS
db_1     | 2019-10-28 12:35:33+00:00 [Note] [Entrypoint]: Switching to dedicated us
db_1     | 2019-10-28 12:35:33+00:00 [Note] [Entrypoint]: Entrypoint script for MyS
db_1     | 2019-10-28T12:35:34.590819Z 0 [Warning] [MY-011070] [Server] 'Disabling k'  port: 3306  MySQL Community Server - GPL.
db_1     | 2019-10-28T12:35:51.209281Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: '/var/run/mysqld/mysqlx.sock' bind-address: '::' port: 33060
wp_1     | [28-Oct-2019 12:35:52 UTC] PHP Warning:  mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'172.18.0.3' (using password: YES) in Standard input code on line 22
wp_1     |
wp_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.3' (using password: YES)
wpcli_1  | Error: Error establishing a database connection.
_wpcli_1 exited with code 1
wp_1     |
wp_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.3' (using password: YES)
wp_1     |
wp_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.3' (using password: YES)
wp_1     |
wp_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.3' (using password: YES)
wp_1     |
wp_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.3' (using password: YES)
wp_1     |
wp_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.3' (using password: YES)
wp_1     |
wp_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.3' (using password: YES)
wp_1     |
wp_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.3' (using password: YES)
wp_1     |
wp_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.3' (using password: YES)
wp_1     |
wp_1     | WARNING: unable to establish a database connection to 'db'
wp_1     |   continuing anyways (which might have unexpected results)
wp_1     |
wp_1     | AH00543: apache2: bad user name 1000
mychildcare_wp_1 exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)
Stopping _pma_1 ... done
Stopping _db_1  ... done
`

**Comment by geeksupport1** [comment]
Here is the log again with \n


>>>>
geek@DESKTOP-O7A5KCN:/e/PROJECT/DOCKER$ docker-compose up
Starting _db_1 ...
Starting _db_1 ... done
Starting _wp_1 ...
Starting _wp_1
Starting _pma_1 ...
Starting _wp_1 ... done
Starting _wpcli_1 ...
Starting _wpcli_1 ... done
Attaching to _db_1, _wp_1, _pma_1, _wpc
db_1     | 2019-10-28 12:35:28+00:00 [Note] [Entrypoint]: Entrypoint script for MyS
db_1     | 2019-10-28 12:35:33+00:00 [Note] [Entrypoint]: Switching to dedicated us
db_1     | 2019-10-28 12:35:33+00:00 [Note] [Entrypoint]: Entrypoint script for MyS
db_1     | 2019-10-28T12:35:34.590819Z 0 [Warning] [MY-011070] [Server] 'Disabling k'  port: 3306  MySQL Community Server - GPL.
db_1     | 2019-10-28T12:35:51.209281Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: '/var/run/mysqld/mysqlx.sock' bind-address: '::' port: 33060
wp_1     | [28-Oct-2019 12:35:52 UTC] PHP Warning:  mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'172.18.0.3' (using password: YES) in Standard input code on line 22
wp_1     |
wp_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.3' (using password: YES)
wpcli_1  | Error: Error establishing a database connection.
_wpcli_1 exited with code 1
wp_1     |
wp_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.3' (using password: YES)
wp_1     |
wp_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.3' (using password: YES)
wp_1     |
wp_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.3' (using password: YES)
wp_1     |
wp_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.3' (using password: YES)
wp_1     |
wp_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.3' (using password: YES)
wp_1     |
wp_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.3' (using password: YES)
wp_1     |
wp_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.3' (using password: YES)
wp_1     |
wp_1     | MySQL Connection Error: (1045) Access denied for user 'root'@'172.18.0.3' (using password: YES)
wp_1     |
wp_1     | WARNING: unable to establish a database connection to 'db'
wp_1     |   continuing anyways (which might have unexpected results)
wp_1     |
wp_1     | AH00543: apache2: bad user name 1000
mychildcare_wp_1 exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)
Stopping _pma_1 ... done
Stopping _db_1  ... done


>>>>>

**Comment by nezhar** [comment]
It looks like there is something wrong with the Apache user: `wp_1 | AH00543: apache2: bad user name 1000`

Try to set the `APACHE_RUN_USER` nad the `APACHE_RUN_GROUP` environment variables in docker-compose.yml.

Also, can you try to use a custom Dockerfile and use this entrypoint script: https://github.com/nezhar/laravel-docker-compose/blob/master/docker/php/entrypoint

Are you running on wsl2? Not sure if this can be related to file permissions.

**Comment by geeksupport1** [comment]
Thanks for replying nezhar.
I've looking into how to do it.
