### ISSUE TITLE
Wrong yaml configuration

### ISSUE THREAD

**Issue by arifamir** [nezhar/wordpress-docker-compose#40]
We need to fix the yaml configuration.
```

volumes:
  db_data:
```
should be replaced by 

```
volumes:
  db_data: {}
```

**Comment by nezhar** [comment]
What effect will this have? The docs of `docker-compose` do not mention that this is required: https://docs.docker.com/compose/compose-file/

Have you run into any issue without the `{}` in the volume declaration?
