### ISSUE TITLE
How to view php logs in this setup?

### ISSUE THREAD

**Issue by jopfre** [nezhar/wordpress-docker-compose#41]

**Comment by mwoodpatrick** [comment]
Can we add something to the readme providing recommendations on how to view apache/php/mysql logs and best practices for debugging & tracing, Pointers to existing online docs would be fine

**Comment by nezhar** [comment]
By default all logs will go to the console. You can extend the configuration located in `config/php.conf.ini` if you need additional settings in PHP.

The Wordpress logging configuration should be done in the wp-config.php according to https://wordpress.org/support/article/debugging-in-wordpress/
