### ISSUE TITLE
How can I enable SOAP client?

### ISSUE THREAD

**Issue by pdmwu** [nezhar/wordpress-docker-compose#47]
I am trying to use the SOAP class using this Docker approach.

How can I install/enable it?

**Comment by nezhar** [comment]
Can you explain a bit more detailed what do you want to do?

If you plan on using the php `SoapClient` you may need to run a custom build and add this to the docker setup: `docker-php-ext-install soap`

You may also take a look at this: https://github.com/nezhar/wordpress-docker-compose/pull/57
