### ISSUE TITLE
Unable to upload theme in to wordpress

### ISSUE THREAD

**Issue by kollisaisriharsha** [nezhar/wordpress-docker-compose#5]
When I tried to upload a theme into WordPress through admin console, it says `The uploaded file exceeds the upload_max_filesize directive in php.ini.` and I can't find the php.ini file to edit the file size limit. 

Can you please guide me on this issue?
Thank you.

**Comment by kadaliao** [comment]
@kollisaisriharsha the php.ini file is in the wordpress docker. 

1. You can add a uploads.ini file  in your project folder. Below is the php settings:

```
file_uploads = On
memory_limit = 500M
upload_max_filesize = 30M
post_max_size = 30M
max_execution_time = 600
```

2. Configure the volume to load the file in the container in the docker-compose.yml
```
volumes:
    - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
```

**Comment by nezhar** [comment]
Added in #4

**Comment by huskenmoon** [comment]
does this still apply to 

PHP Version 7.2.18
--
???????????
and if there is a video that will be pretty helpful
