### ISSUE TITLE
wpcli_1 exited with code 0

### ISSUE THREAD

**Issue by jhorgint** [nezhar/wordpress-docker-compose#53]
Starting clubby-tachira_db_1 ... done
Starting clubby-tachira_pma_1 ... done
Starting clubby-tachira_wp_1  ... done
Starting clubby-tachira_wpcli_1 ... done
Attaching to clubby-tachira_db_1, clubby-tachira_pma_1, clubby-tachira_wp_1, clubby-tachira_wpcli_1
db_1     | 2020-04-09 21:58:11+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.19-1debian10 started.
db_1     | 2020-04-09 21:58:11+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db_1     | 2020-04-09 21:58:11+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.19-1debian10 started.
db_1     | 2020-04-09T21:58:11.572436Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using this option as it' is deprecated and will be removed in a future release.
db_1     | 2020-04-09T21:58:11.572540Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.19) starting as process 1
pma_1    | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
pma_1    | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
pma_1    | [Thu Apr 09 21:58:13.173908 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.4.4 configured -- resuming normal operations
pma_1    | [Thu Apr 09 21:58:13.173961 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
wp_1     | [09-Apr-2020 21:58:13 UTC] PHP Warning:  mysqli::__construct(): (HY000/2002): Connection refused in Standard input code on line 22
wp_1     |
wp_1     | MySQL Connection Error: (2002) Connection refused
db_1     | 2020-04-09T21:58:14.952015Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
db_1     | 2020-04-09T21:58:15.077161Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
db_1     | 2020-04-09T21:58:15.554287Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.19'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
db_1     | 2020-04-09T21:58:15.710874Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: '/var/run/mysqld/mysqlx.sock' bind-address: '::' port: 33060
wp_1     | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.4. Set the 'ServerName' directive globally to suppress this message
wp_1     | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.4. Set the 'ServerName' directive globally to suppress this message
wp_1     | [Thu Apr 09 21:58:16.889768 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.3.16 configured -- resuming normal operations
wp_1     | [Thu Apr 09 21:58:16.891339 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
clubby-tachira_wpcli_1 exited with code 0

************************
I don't sure if it is a real problem.
I want to add a second Wordpress to test Underscore theme alongside the "Unit test data" but I only want this Data "unit test data" available for this instance of wordpress. could you please show me how

**Comment by flip111** [comment]
wpcli is a command line utility. I'm not sure why it was started, maybe to setup something or maybe just to test if it works. Anyway it's not supposed to keep running that's why it stops (exits). The return code 0 is to indicate that there were no errors during running wpcli.

Close this issue if this answer satisfies you.

**Comment by jhorgint** [comment]
absolutely yes, thanks for your reply.
