### ISSUE TITLE
phpMyAdmin installation and configuration

### ISSUE THREAD

**Issue by flip111** [nezhar/wordpress-docker-compose#56]
Would be nice to have the full installation of phpMyAdmin with all it's features. Here is the setup procedure https://docs.phpmyadmin.net/en/latest/setup.html#phpmyadmin-configuration-storage

Additionally an expiration time longer than 1440 seconds on the panel would be good (no expiration) ?

And exposing of the phpMyAdmin config file.

**Comment by nezhar** [comment]
I was thinking about this for a while, to make it more accessible, but also not making the build more complicated when someone needs a specific version of WordPress. Would you like to take a look at https://github.com/nezhar/wordpress-docker-compose/pull/57?

**Comment by nezhar** [comment]
I think the documentation mentioned in https://github.com/nezhar/wordpress-docker-compose/pull/55 does the job pretty well.

**Comment by flip111** [comment]
The environment variables don't allow for full config over phpMyAdmin. For example the expiration time can not be configured in this way. For this access to the php configuration file is required.

**Comment by flip111** [comment]
Maybe the php configuration file can be mapped in a similar way as commented in https://github.com/nezhar/wordpress-docker-compose/issues/51#issuecomment-622122420 ?
