### ISSUE TITLE
Changes in "style.css" don't work (Why)

### ISSUE THREAD

**Issue by jhorgint** [nezhar/wordpress-docker-compose#59]
changes in "style.css" located in "wp-app\wp-content\themes\mi-tema" don't sync with the "style.css" loaded in the chrome browser.
all is running ok.
I am using Docker 2.3.0.2 and Windows 10 (with linux containers)
I not have idea what I need to make it happend

**Comment by flip111** [comment]
Clear your browser cache. Or use a HTTP client like curl to check what you are actually getting from the server.

**Comment by jhorgint** [comment]
> Clear your browser cache. Or use a HTTP client like curl to check what you are actually getting from the server.

**Comment by jhorgint** [comment]
thanks a lot, I'm going to try it.

**Comment by flip111** [comment]
@jhorgint can you close this issue ?

**Comment by jhorgint** [comment]
yes sure
