### ISSUE TITLE
Please add to README: How do I make it run on https?

### ISSUE THREAD

**Issue by borisdiakur** [nezhar/wordpress-docker-compose#6]
What are the steps required to make the site run on https? Currently, if I change the wordpress address url and the site url to https://wp-app.local I cannot access the admin area anymore.

**Comment by nezhar** [comment]
I added a commit into another branch: [https](/nezhar/wordpress-docker-compose/tree/https)
This uses a separate dockerfile that enables the self-signed certificate that Apache uses by default.

**Comment by borisdiakur** [comment]
Thanks a lot! I’ll have a look today and will close the issue.

**Comment by cannap** [comment]
Hi i tried but it tells me its not secure do i need to change something?

**Comment by nezhar** [comment]
@cannap It's because the certificate is self-signed, you just have to skip the warning of the browser in this case.
