### ISSUE TITLE
Make site available to the lan?

### ISSUE THREAD

**Issue by palomnik** [nezhar/wordpress-docker-compose#64]
This is probably a simple issue of docker ignorance on my part.
Is there a way to make the website available to the LAN and not just the localhost?

**Comment by flip111** [comment]
it should be available on LAN by default.

1. get the right port as in the config
2. get your lan ip
3. check if you have no firewall or the right firewall rules.

can you close this issue when it answered your question?

**Comment by palomnik** [comment]
No, I get a "could not connect to server" from any machine on the LAN, except the host machine.
I have no firewall on the host machine (running Linux Mint).
I'll try again a bit later with a Mac machine.

**Comment by palomnik** [comment]
I brought up the site on a mac - same exact issue.  I can access the site from the host on which it is running, but cannot connect from any other machine on the lan.

**Comment by flip111** [comment]
@palomnik you can use the `netstat` command or google "how to see open ports on linux", then when you see a running service it's a network problem. This doesn't look like a problem with wordpress-docker-compose

**Comment by palomnik** [comment]
I had to change .env from 127.0.0.1 to 0.0.0.0 and then it worked.
