### ISSUE TITLE
Loopback and Rest Issues?

### ISSUE THREAD

**Issue by palomnik** [nezhar/wordpress-docker-compose#65]
There are two issues when checking out the health page from the WordPress dashboard:

The REST API encountered an error
Your site could not complete a loopback request

I think that these are often issues with WordPress in docker.  Does anyone know how to fix these?

**Comment by palomnik** [comment]
The problem only occurs when using another port other than 80:80, e.g. 8005:80.

It would be nice if there was a workaround for this.

**Comment by flip111** [comment]
https://hub.docker.com/_/wordpress/?tab=reviews

```
Note that if the internal port and external port are different, like the 8080:80 that is mentioned in the description and the stack.yml, the Wordpress health check will complain that the loopback connection doesn't work. Certain things will not work in that situation.

This is because within the container, the listening port is 80, but the loopback connection tries to connect to the external port as seen by a browser.

Not sure the best way to overcome that, apart from to make the internal and external ports the same as each other.
```

---

@palomnik can you close the issue here and instead report upstream at

https://github.com/docker-library/official-images

and

https://make.wordpress.org/core/handbook/testing/reporting-bugs/
