### ISSUE TITLE
Run a few installations at the same time on 80 port

### ISSUE THREAD

**Issue by proger-su** [nezhar/wordpress-docker-compose#85]
Hi guys!
Is it possible to run a few installations at the same time on 80 port? 
So far I have managed to do this on different ports. Ex: http://firstsite.local:8181 and http://secondsite.local:8282

Thanks a lot!

**Comment by nezhar** [comment]
Sure, you can use a different `IP` configuration in the `.env` of each project.

**Comment by proger-su** [comment]
> Sure, you can use a different `IP` configuration in the `.env` of each project.

Yeh, but could you give some example, please?

**Comment by nezhar** [comment]
In you `.env` file you can use:

```
IP=127.0.0.2
```

Define a new IP for every project, this way they can all run in parallel. You also need to make sure the port you are using for the binding is not already in use for the selected IP.

**Comment by nezhar** [comment]
You can also make use of https://github.com/nezhar/wordpress-docker-compose/pull/86 and now define the `PORT` in the `.env,` file
