### ISSUE TITLE
What is the difference to wp-env

### ISSUE THREAD

**Issue by datengraben** [nezhar/wordpress-docker-compose#87]
Hey, I really like the effort here. I'm new to wordpress development and realized there is not much of an open source effort for developer plugins like this, either it's wordpress/automaticc repos, not well documented, commercial plugin/repo or does not exist at all, so I really like it!

* Maybe you can clarify whats the difference to [`wp-env`](https://www.npmjs.com/package/@wordpress/env) or whats the rationale behind this repository. The only difference I can spot at the moment is, that you are not bound to node and npm, when using the tool of this repo.

Thank you,
Chris

**Comment by nezhar** [comment]
This repository is giving you a way to run WordPress is a containerzired environment and some methods on how to link volumes for themes, plugins or the entire source code. I started this about six year ago as I required a development environment that can be reproduced on other development machines.

Building and testing themes/plugins also become a part of this repository as there was no better alternative at that time. It seems from your resource that [wp-env](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-env/) is a convinient way to do this task now and also allows to integrate automated tests. Under the hood it probably uses a similar approach, but you have the support and the resources of the maintainers and the community.

I may also give it a try by moving https://github.com/nezhar/anexia-monitoring-wordpress-tests
