### ISSUE TITLE
Specify a port on .env to run db on (when we are running more than one db on a server)

### ISSUE THREAD

**Issue by cauafroes** [nezhar/wordpress-docker-compose#90]
this worked wonders for me, but i change db ports often, so i locally changed my .env to have  DB_port entry:
`DB_PORT=5460`
and used this var in the compose.yml mysql port:
`${IP}:${DB_PORT}:3306`
      
would be interesting to have that on the main branch or is my cenario too specific?

**Comment by mughalmuneeb786** [comment]
please read this post you understand ports with docker 
https://ioflood.com/blog/docker-compose-ports-vs-expose-explained/
@cauafroes

**Comment by cauafroes** [comment]
will read it, thanks
