### ISSUE TITLE
WordPress Redirects to IP Address Instead of Domain

### ISSUE THREAD

**Issue by ErminMerdanovic** [nezhar/wordpress-docker-compose#92]
Hello everyone, I'm currently in the process of setting up WordPress using Docker Compose and Apache which is running on the host as a reverse proxy (unfortunately, I can't use nginx). Additionally, I use Cloudflare. When I attempt to access the site using the domain, I encounter an immediate redirect to "https://127.0.0.1:8585/wp-admin/install.php" instead of the desired "https://domain.com/wp-admin/install.php". To address this, I modified the configuration by adding the following two lines:

```
define('WP_HOME','https://domain.com');
define('WP_SITEURL','https://domain.com');
```

This adjustment successfully resolves the issue, but I'm uncertain whether this is the optimal approach. I would greatly appreciate any assistance or guidance on whether this method is appropriate, or if there's an alternative solution that can be implemented through Docker Compose environment variables. Thank you for your insights.

Edit: Unfortunately, when attempting to proceed with the above settings, I encountered again an issue. After completing the WordPress setup and attempting to access the main page of the WordPress site using the domain, I was redirected again to the IP address "https://127.0.0.1/". Is there anyone who has a solution for this problem?

**Comment by mughalmuneeb786** [comment]
Did you try to edit the yaml host settings for nginx? like below try this and let me know thanks .I hope this works .
`server {
  listen 80;
  server_name yourdomaine.com;

  location / {
    proxy_pass http://0.0.0.0:3001;
    proxy_read_timeout  90;
    proxy_redirect http://0.0.0.0:3001 http://yourdomaine.com/;
  }
}`

**Comment by kczereczon** [comment]
Same

**Comment by nezhar** [comment]
Please try some of the solutions mentioned [here](https://wordpress.org/support/topic/wordpress-site-with-docker-behind-apache-reverse-proxy-keeps-redirecting-from-do/).

Have you tried disabling some of the plugins, especially those that are related to caching?

**Comment by kczereczon** [comment]
Hello, It might be problem with Nginx / Firewall config problem not with Wordpress by itself.

**Comment by kczereczon** [comment]
Yes it was problem with Nginx it occurred when force ssl has been enabled.
