### ISSUE TITLE
Wordpress very slow

### ISSUE THREAD

**Issue by FractalMind** [nezhar/wordpress-docker-compose#94]
Every page and action takes like 5 to 10 seconds.

I searched the issue and found:
https://stackoverflow.com/questions/54291859/docker-wordpress-super-slow

The problem comes from the docker mount.
 volumes:
    - ./wordpress-storage:/var/www/html

Every time WordPress loads a page from the volume it has to go through a lot of processes.

If I remove
 volumes:
    - ./wordpress-storage:/var/www/html

The site is blazing fast. 
Any update we can do to fix that?

**Comment by DDSNA** [comment]
Have you had any success dealing with this?

**Comment by nezhar** [comment]
This might be related to windows. Maybe try to run it using [WSL](https://learn.microsoft.com/en-us/windows/wsl/install)

**Comment by DDSNA** [comment]
@nezhar not related to windows, could be reproduced on Linux and Windows
