### ISSUE TITLE
Error: Your site is unable to reach WordPress.org at 198.143.164.251, and returned the error: cURL error 6: getaddrinfo() thread failed to start

### ISSUE THREAD

**Issue by edgardmello** [nezhar/wordpress-docker-compose#95]
Unable to access internet in wp-admin

Error: Your site is unable to reach WordPress.org at 198.143.164.251, and returned the error: cURL error 6: getaddrinfo() thread failed to start

I'm using ubuntu 22.04 in a proxmox server. Had the same issue in a lxc container setup. Both containers are accessing internet ok. As I could not run ping or use apt to install network tools in the Wordpress container I could not check internet access from the wp container.

**Comment by nezhar** [comment]
Have you tried the steps documented in [project from existing source](https://github.com/nezhar/wordpress-docker-compose?tab=readme-ov-file#project-from-existing-source)?
