### ISSUE TITLE
cant install new plugins

### ISSUE THREAD

**Issue by kezern** [nezhar/wordpress-docker-compose#96]
I'm trying to install new plugins and I'm getting Installation failure, file could not be copied.
I'm using macos sonoma.

**Comment by omonefe08** [comment]
it may be something i cant help with

**Comment by nezhar** [comment]
This might be related to fie permission, are you using a the full project volume configuration?

Have you tried setting [user id and group id](https://stackoverflow.com/questions/40462189/docker-compose-set-user-and-group-on-mounted-volume)?
